version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apiregister
      MYSQL_USER: joaop
      MYSQL_PASSWORD: 123
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80:80
    environment:
      MYSQL_USERNAME: 'joaop'
      MYSQL_ROOT_PASSWORD: '123'
